# Generated by Django 3.0.6 on 2020-06-02 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('house_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gender_kind', models.IntegerField(choices=[(1, "boys' party"), (2, "girls' party"), (3, 'mixed party')], default=3)),
            ],
        ),
        migrations.CreateModel(
            name='PunishCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=300)),
                ('level', models.CharField(choices=[(1, 'No.1 Rank'), (2, 'No.2 Rank'), (3, 'No.3 Rank')], default=1, max_length=10)),
                ('kind', models.CharField(choices=[('truth', '真心话'), ('challenge', '大冒险'), ('special_magic_card', '魔法卡片')], default='truth', max_length=20)),
                ('is_front', models.BooleanField(default=False)),
                ('gender', models.IntegerField(choices=[(1, "boys' party"), (2, "girls' party"), (3, 'mixed party')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('openid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nick_name', models.CharField(max_length=100)),
                ('head_pic', models.ImageField(upload_to='uploads/')),
                ('if_inhouse', models.BooleanField(default=False)),
                ('if_ready', models.BooleanField(default=True)),
                ('if_being_punished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PunishChoose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('if_change', models.BooleanField(default=False)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragonking.PunishCard')),
                ('user_openid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragonking.User')),
            ],
        ),
        migrations.CreateModel(
            name='HouseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragonking.House')),
                ('user_openid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragonking.User')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='house_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragonking.User'),
        ),
    ]
