# Generated by Django 3.0.6 on 2020-05-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='punishcard',
            name='is_main_page',
            field=models.BooleanField(default=False),
        ),
    ]
