# Generated by Django 3.0.6 on 2020-06-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='head_pic',
            field=models.CharField(max_length=200),
        ),
    ]
