# Generated by Django 3.0.6 on 2020-05-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonking', '0002_punishcard_is_main_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='punishcard',
            old_name='is_main_page',
            new_name='is_front',
        ),
        migrations.AddField(
            model_name='house',
            name='gender_kind',
            field=models.IntegerField(choices=[(1, "boys' party"), (2, "girls' party"), (3, 'mixed party')], default=1),
        ),
        migrations.AddField(
            model_name='punishcard',
            name='gender',
            field=models.IntegerField(choices=[(1, "boys' party"), (2, "girls' party"), (3, 'mixed party')], default=1),
        ),
    ]
