# Generated by Django 3.0.7 on 2020-07-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonking', '0002_auto_20200602_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='if_ready',
            field=models.BooleanField(default=False),
        ),
    ]
