# Generated by Django 3.0.6 on 2020-05-27 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dragonking', '0003_auto_20200527_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punishchoose',
            name='punish_or_challenge',
        ),
    ]
