# Generated by Django 3.0.6 on 2020-05-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonking', '0004_remove_punishchoose_punish_or_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punishcard',
            name='level',
            field=models.CharField(choices=[('one', 'No.1 Rank'), ('two', 'No.2 Rank'), ('three', 'No.3 Rank')], default='one', max_length=10),
        ),
    ]
