# Generated by Django 3.0.6 on 2020-05-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonking', '0005_auto_20200528_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punishcard',
            name='level',
            field=models.CharField(choices=[(1, 'No.1 Rank'), (2, 'No.2 Rank'), (3, 'No.3 Rank')], default='one', max_length=10),
        ),
    ]
