# Generated by Django 3.0.6 on 2020-05-29 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dragonking', '0006_auto_20200529_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='house_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dragonking.House'),
        ),
    ]
