# Generated by Django 3.0.6 on 2020-05-29 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dragonking', '0007_auto_20200529_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='house_id',
        ),
    ]
